### ISSUE TITLE
Make README instructions more digestible

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/typescript-analyze-trace#29]
With a bit of time, someone using this tool can probably figure out what commands to run - but if we could make it clearer from a quick glance to

```
just run this!
```

with codeblocks and and headings and the like, we can make the process feel less overwhelming.

**Comment by DanielRosenwasser** [comment]
We should also explicitly link to the npm download page.

**Comment by dylang** [comment]
Also
 * An example of the output.
 * What problems this is useful for solving.
 * How to grok the output, like are `hot spots` good or bad? 
 * How should we use the results?

**Comment by DanielRosenwasser** [comment]
I put up some possible new content at https://github.com/microsoft/typescript-analyze-trace/pull/30 if you'd like to weigh in @dylang
