### ISSUE TITLE
output can break if data is too big

### ISSUE THREAD

**Issue by dylang** [microsoft/typescript-analyze-trace#33]
Something here is breaking, because it's cutting off our output.

```ts
    return new Promise<ProjectResult>(resolve => {
        const child = cp.fork(path.join(__dirname, "analyze-trace-file"), args, { stdio: "pipe" });

        let stdout = "";
        let stderr = "";

        child.stdout!.on("data", chunk => stdout += chunk);
        child.stderr!.on("data", chunk => stderr += chunk);

        child.on("exit", (code, signal) => {
            resolve({
                project,
                stdout: stdout.trim(),
                stderr: stderr.trim(),
                exitCode: code ?? undefined,
                signal: signal ?? undefined,
            });
        });
    });
```

If we run `analyze-trace-file` on the command line with the same arguments it works fine.

I tried setting `maxBuffer` but that's not an option for `fork`, and even if I changed it to `exec` it still fails with the same problem.

This is what it looks like when the output gets cut off. Maybe `exit` is being fired before all of `on('data')` had a chance to fire?

<img width="638" alt="Screen Shot 2022-09-21 at 5 55 47 PM" src="https://user-images.githubusercontent.com/51505/191617776-2742a84a-97a5-4343-bd40-bccac0236cd4.png">

**Comment by amcasey** [comment]
Oh, that should probably just be `on("close"`.  I didn't understand the difference at the time (and I may not now 😆).

**Comment by amcasey** [comment]
@dylang Would you mind validating that fix locally before I put up a PR?

**Comment by dylang** [comment]
Hi @amcasey - I tried when making the ticket `on('close')` but it didn't fix it.

I even went to the extreme, adding a `setTimeout` in case there was some buffer weirdness, but it didn't help.

```ts
        // did not fix it
        child.on("close", (code, signal) => {
            // also did not fix it
            setTimeout(() => {
                console.log('exit', code, signal, data, args[0], stdout, '---DONE DYLAN--')
                resolve({
                    project,
                    stdout: stdout.join(''),
                    stderr: stderr.join(''),
                    exitCode: code !== null && code !== void 0 ? code : undefined,
                    signal: signal !== null && signal !== void 0 ? signal : undefined,
                });
                
            }, 1000);
        });

**Comment by amcasey** [comment]
@dylang Unfortunately, that's the extent of my ability to diagnose the problem by code inspection.  Do you have a repro you can share?

**Comment by amcasey** [comment]
Huh, it looks like calling [`process.exit`](https://nodejs.org/api/process.html#processexitcode) in the child can do that.  So I guess I have to revisit _all_ of my tools...

**Comment by dylang** [comment]
thanks for making the PR! I've added feedback in the PR comments.

**Comment by dylang** [comment]
When I use my workaround, holy crap so many more insights are outputed!

I'm guessing over a dozen levels of nesting isn't good for performance. It might be more, I hit control-c at this point.

<img width="1297" alt="Screen Shot 2022-09-23 at 11 15 46 AM" src="https://user-images.githubusercontent.com/51505/191994851-c188d874-bf90-4085-a18f-d7be08181b68.png">
